// created_files/React/react_export/src/qlib/qrow/QRow.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { useNavigate } from "react-router-dom";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const QRow = ({
  width,
  height,
  bgColor,
  bgUrl,
  isImageFill,
  children,
  isAbsoluteValue,
  onClick = "",
  action = "",
  navigation = "",

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType = "",
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  maxValue,
  minValue,
  midValue,

  zIndex,
  tailwaindClasses,
  backgroundSize,
  boxShadow,
  textShadow,
  style
}) => {
  const rowRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [hasAnimated, setHasAnimated] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true);
        }
      },
      { threshold: 0.2 }
    );

    if (rowRef.current) observer.observe(rowRef.current);
    return () => rowRef.current && observer.unobserve(rowRef.current);
  }, [hasAnimated]);

  useEffect(() => {
    if (isAnimationP === "true" && isVisible) {
      runDynamicAnimations({
        ref: rowRef,
        isVisible,
        isAnimationP,
        animationType,
        animationDirection,
        animationEasing,
        animationIterations,
        animationDelay,
        animationDuration,
        isRevarsed,
        maxValue,
        minValue,
        midValue,
      });
    }
  }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes" && action === "Navigate to" && navigation) {
      navigate(`/${navigation}`);
    }
  };

  const rowStyle = {
    ...generateStyle(
      Object.fromEntries(
        Object.entries({
          width,
          height,
          isAbsoluteValue,
          bgColor,
          bgUrl,
          isImageFill,
          zIndex,
          backgroundSize,
          boxShadow,
          textShadow
        }).filter(([, val]) => val !== undefined && val !== null && val !== "")
      )
    ),
    // display: "flex",
    // flexDirection: "row",
  };

  return (
    <div
      ref={rowRef}
      className={tailwaindClasses || ""}
      style={{...rowStyle, ...style}}
      onClick={onClick === "Yes" ? handleClick : undefined}
    >
      {children}
    </div>
  );
};

// ✅ PropTypes for only used props
QRow.propTypes = {
  bgColor: PropTypes.string,
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  children: PropTypes.node,
  isAbsoluteValue: PropTypes.bool,
  onClick: PropTypes.string,
  action: PropTypes.string,
  navigation: PropTypes.string,

  isAnimationP: PropTypes.string,
  animationEasing: PropTypes.string,
  animationDirection: PropTypes.string,
  animationType: PropTypes.string,
  animationIterations: PropTypes.string,
  animationDelay: PropTypes.string,
  animationDuration: PropTypes.string,
  animationCurve: PropTypes.string,
  animationTargetPosition: PropTypes.string,
  isRevarsed: PropTypes.string,

  zIndex: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  tailwaindClasses: PropTypes.string,
  backgroundSize: PropTypes.string,
  boxShadow: PropTypes.string,
};

export default QRow;
QRow.displayName = "QRow";

// created_files/Vue/vue_export/src/qlib/qrow/QRow.vue
<script setup>
import { ref, onMounted, onUnmounted, watch, computed } from "vue";
import { useRouter } from "vue-router";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  width: String,
  height: String,
  bgColor: String,
  bgUrl: String,
  isImageFill: Boolean,
  isAbsoluteValue: String,
  onClick: { type: String, default: "" },
  action: { type: String, default: "" },
  navigation: { type: String, default: "" },

  // Animation Props
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: { type: String, default: "" },
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,

  zIndex: [String, Number],
  tailwaindClasses: String,
  backgroundSize: String,
  boxShadow: String,
  textShadow: String,
  style: Object,
  maxValue: String,
  minValue: String,
  midValue: String,
});

const router = useRouter();
const rowRef = ref(null);
const isVisible = ref(false);
const hasAnimated = ref(false);
const observer = ref(null);

onMounted(() => {
  observer.value = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 },
  );
  if (rowRef.value) observer.value.observe(rowRef.value);
});

onUnmounted(() => {
  if (observer.value && rowRef.value) observer.value.unobserve(rowRef.value);
});

watch(isVisible, (val) => {
  if (props.isAnimationP === "true" && val) {
    runDynamicAnimations({
      ref: { current: rowRef.value },
      isVisible: val,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      animationDuration: props.animationDuration,
      isRevarsed: props.isRevarsed,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });
  }
});

const handleClick = () => {
  if (
    props.onClick === "Yes" &&
    props.action === "Navigate to" &&
    props.navigation
  ) {
    router.push(`/${props.navigation}`);
  }
};

const rowStyle = computed(() => {
  const definedProps = Object.entries({
    width: props.width,
    height: props.height,
    isAbsoluteValue: props.isAbsoluteValue,
    bgColor: props.bgColor,
    bgUrl: props.bgUrl,
    isImageFill: props.isImageFill,
    zIndex: props.zIndex,
    backgroundSize: props.backgroundSize,
    boxShadow: props.boxShadow,
    textShadow: props.textShadow,
  }).filter(([, val]) => val !== undefined && val !== null && val !== "");

  return {
    ...generateStyle(Object.fromEntries(definedProps)),
  };
});
</script>

<template>
  <div
    ref="rowRef"
    :class="tailwaindClasses"
    :style="{ ...rowStyle, ...style }"
    @click="handleClick"
  >
    <slot></slot>
  </div>
</template>
