// created_files/React/react_export/src/qlib/qflex/QFlex.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { useNavigate } from "react-router-dom";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const QFlex = ({
  width,
  height,
  bgColor,
  bgUrl,
  isImageFill,
  children,
  isAbsoluteValue,
  onClick = "",
  action = "",
  navigation = "",

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType = "",
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  maxValue,
  minValue,
  midValue,

  zIndex,
  tailwaindClasses,
  backgroundSize,
  boxShadow,
  textShadow,
  style
}) => {
  const divRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [hasAnimated, setHasAnimated] = useState(false);
  const [classes, setClasses] = useState("");

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true);
        }
      },
      { threshold: 0.2 }
    );

    if (divRef.current) observer.observe(divRef.current);
    return () => divRef.current && observer.unobserve(divRef.current);
  }, [isVisible, hasAnimated]);

  useEffect(() => {
    const applyAnimations = async () => {
      if (isAnimationP === "true" && isVisible) {
        const cleanup = await runDynamicAnimations({
          ref: divRef,
          isVisible,
          isAnimationP,
          animationType,
          animationDirection,
          animationEasing,
          animationIterations,
          animationDelay,
          animationDuration,
          isRevarsed,
          maxValue,
          minValue,
          midValue,
        });

        setClasses(divRef.current.className);
      }
    };

    applyAnimations();
  }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes" && action === "Navigate to" && navigation) {
      navigate(`/${navigation}`);
    }
  };

  const containerStyle = {
    ...generateStyle(
      Object.fromEntries(
        Object.entries({
           width,
          height,
          isAbsoluteValue,
          bgColor,
          bgUrl,
          isImageFill,
          zIndex,
          backgroundSize,
          boxShadow,
          textShadow
        }).filter(([, val]) => val !== undefined && val !== null && val !== "")
      )
    ),
    // ...(isAnimationP === "true" && !hasAnimated && { opacity: 0 }),
    ...(isAnimationP === "true" && animationType?.toLowerCase() !== "none" && !hasAnimated && { opacity: 0 }),
  };

  return (
    <div
      ref={divRef}
      onClick={onClick === "Yes" ? handleClick : undefined}
       style={{
          ...containerStyle,
          ...style
        }}
      className={`${classes} ${tailwaindClasses || ""}`}
    >
      {children}
    </div>
  );
};

QFlex.propTypes = {
  bgColor: PropTypes.string,
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  children: PropTypes.node,
  isAbsoluteValue: PropTypes.bool,
  onClick: PropTypes.string,
  action: PropTypes.string,
  navigation: PropTypes.string,

  isAnimationP: PropTypes.string,
  animationEasing: PropTypes.string,
  animationDirection: PropTypes.string,
  animationType: PropTypes.string,
  animationIterations: PropTypes.string,
  animationDelay: PropTypes.string,
  animationDuration: PropTypes.string,
  animationCurve: PropTypes.string,
  animationTargetPosition: PropTypes.string,
  isRevarsed: PropTypes.string,

  zIndex: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  tailwaindClasses: PropTypes.string,
  backgroundSize: PropTypes.string,
  boxShadow: PropTypes.string,
};

export default QFlex;
QFlex.displayName = "QFlex";

// created_files/Vue/vue_export/src/qlib/qflex/QFlex.vue
<template>
  <div
    ref="divRef"
    @click="handleClick"
    :class="[classes, tailwaindClasses]"
    :style="combinedStyle"
  >
    <slot></slot>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, watch, computed } from "vue";
import { useRouter } from "vue-router";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  width: String,
  height: String,
  bgColor: String,
  bgUrl: String,
  isImageFill: [Boolean, String],
  isAbsoluteValue: [Boolean, String],
  onClick: String,
  action: String,
  navigation: String,
  // Animation Props
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: String,
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  zIndex: [String, Number],
  tailwaindClasses: String,
  backgroundSize: String,
  boxShadow: String,
  textShadow: String,
  style: Object,
  maxValue: String,
  minValue: String,
  midValue: String,
});

const divRef = ref(null);
const router = useRouter();
const isVisible = ref(false);
const hasAnimated = ref(false);
const classes = ref("");

onMounted(() => {
  const observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 },
  );

  if (divRef.value) {
    observer.observe(divRef.value);
  }

  onUnmounted(() => {
    if (divRef.value) observer.unobserve(divRef.value);
  });
});

watch(isVisible, async (val) => {
  if (props.isAnimationP === "true" && val) {
    const reactRefMock = { current: divRef.value };
    await runDynamicAnimations({
      ref: reactRefMock,
      isVisible: val,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      animationDuration: props.animationDuration,
      isRevarsed: props.isRevarsed,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });

    classes.value = divRef.value.className;
  }
});

const handleClick = () => {
  if (
    props.onClick === "Yes" &&
    props.action === "Navigate to" &&
    props.navigation
  ) {
    if (router) router.push(`/${props.navigation}`);
  }
};

const combinedStyle = computed(() => {
  // Filter style props
  const styleProps = {
    width: props.width,
    height: props.height,
    isAbsoluteValue: props.isAbsoluteValue,
    bgColor: props.bgColor,
    bgUrl: props.bgUrl,
    isImageFill: props.isImageFill,
    zIndex: props.zIndex,
    backgroundSize: props.backgroundSize,
    boxShadow: props.boxShadow,
    textShadow: props.textShadow,
  };

  const filteredProps = Object.fromEntries(
    Object.entries(styleProps).filter(
      ([, val]) => val !== undefined && val !== null && val !== "",
    ),
  );

  const baseStyle = generateStyle(filteredProps);

  const animationStyle =
    props.isAnimationP === "true" &&
    props.animationType?.toLowerCase() !== "none" &&
    !hasAnimated.value
      ? { opacity: 0 }
      : {};

  return {
    ...baseStyle,
    ...animationStyle,
    ...props.style,
  };
});
</script>
