// created_files/Vue/vue_export/src/qlib/qtablewrapper/QTableWrapper.vue
<template>
  <div ref="tableWrapperRef" @click="handleClick" :style="containerStyle">
    <slot></slot>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { useRouter } from "vue-router";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  width: [String, Number],
  height: [String, Number],
  padding: String,
  paddingLeft: String,
  paddingTop: String,
  paddingRight: String,
  paddingBottom: String,
  margin: String,
  marginLeft: String,
  marginTop: String,
  marginRight: String,
  marginBottom: String,
  positionedLeft: String,
  positionedTop: String,
  positionedRight: String,
  positionedBottom: String,
  color: String,
  bgColor: String,
  borderRadius: [String, Number],
  borderColor: String,
  borderWidth: [String, Number],
  bgUrl: String,
  isImageFill: [Boolean, String],
  widthType: String,
  heightType: String,
  widthPercent: [String, Number],
  heightPercent: [String, Number],
  alignment: String,
  mainAlignment: String,
  crossAlignment: String,
  borderTLR: [String, Number],
  borderTRR: [String, Number],
  borderBLR: [String, Number],
  borderBRR: [String, Number],
  borderTW: [String, Number],
  borderTC: String,
  borderBW: [String, Number],
  borderBC: String,
  borderLW: [String, Number],
  borderLC: String,
  borderRW: [String, Number],
  borderRC: String,
  shadowSpreadRadius: [String, Number],
  shadowBlurRadius: [String, Number],
  shadowOffsetX: [String, Number],
  shadowOffsetY: [String, Number],
  shadowColor: String,
  isAbsoluteValue: [Boolean, String],
  onClick: { type: String, default: "" },
  action: String,
  navigation: String,
  // Animation Props
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: { type: String, default: "" },
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  overflow: String,
  zIndex: [String, Number],
  maxValue: String,
  minValue: String,
  midValue: String,
});

const tableWrapperRef = ref(null);
const router = useRouter();
const isVisible = ref(false);
const hasAnimated = ref(false);

let observer = null;

onMounted(() => {
  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true; // Prevents the animation from running again
      }
    },
    { threshold: 0.2 }
  );

  if (tableWrapperRef.value) {
    observer.observe(tableWrapperRef.value);
  }
});

onUnmounted(() => {
  if (observer && tableWrapperRef.value) {
    observer.unobserve(tableWrapperRef.value);
  }
});

watch(isVisible, (newVal) => {
  if (props.isAnimationP === "true" && newVal) {
    runDynamicAnimations({
      ref: tableWrapperRef,
      isVisible: newVal,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      isRevarsed: props.isRevarsed,
      animationDuration: props.animationDuration,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });
  }
});

const handleClick = () => {
  if (props.onClick === "Yes") {
    switch (props.action) {
      case "Navigate to":
        if (router && props.navigation) router.push(`/${props.navigation}`);
        break;
    }
  }
};

const containerStyle = computed(() => ({
  ...generateStyle({
    width: props.width,
    height: props.height,
    isAbsoluteValue: props.isAbsoluteValue,
    positionedLeft: props.positionedLeft,
    positionedTop: props.positionedTop,
    positionedRight: props.positionedRight,
    positionedBottom: props.positionedBottom,
    bgColor: props.bgColor,
    bgUrl: props.bgUrl,
    isImageFill: props.isImageFill,
    color: props.color,
    borderRadius: props.borderRadius,
    borderTLR: props.borderTLR,
    borderTRR: props.borderTRR,
    borderBLR: props.borderBLR,
    borderBRR: props.borderBRR,
    borderWidth: props.borderWidth,
    borderColor: props.borderColor,
    borderTW: props.borderTW,
    borderBW: props.borderBW,
    borderLW: props.borderLW,
    borderRW: props.borderRW,
    borderTC: props.borderTC,
    borderBC: props.borderBC,
    borderLC: props.borderLC,
    borderRC: props.borderRC,
    paddingLeft: props.paddingLeft,
    paddingRight: props.paddingRight,
    paddingTop: props.paddingTop,
    paddingBottom: props.paddingBottom,
    marginLeft: props.marginLeft,
    marginRight: props.marginRight,
    marginTop: props.marginTop,
    marginBottom: props.marginBottom,
    shadowOffsetX: props.shadowOffsetX,
    shadowOffsetY: props.shadowOffsetY,
    shadowBlurRadius: props.shadowBlurRadius,
    shadowSpreadRadius: props.shadowSpreadRadius,
    shadowColor: props.shadowColor,
    overflow: props.overflow,
    mainAlignment: props.mainAlignment,
    crossAlignment: props.crossAlignment,
    onClick: props.onClick,
    zIndex: props.zIndex,
  }),
  display: "flex",
  flexDirection: "column",
}));
</script>

// created_files/React/react_export/src/qlib/qtablewrapper/QTableWrapper.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { convertedWidth, convertedHeight } from "../../utils/helper";
import { useNavigate } from "react-router-dom";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const QTableWrapper = ({
  width,
  height,
  padding,
  paddingLeft,
  paddingTop,
  paddingRight,
  paddingBottom,
  margin,
  marginLeft,
  marginTop,
  marginRight,
  marginBottom,
  positionedLeft,
  positionedTop,
  positionedRight,
  positionedBottom,
  color,
  bgColor,
  borderRadius,
  borderColor,
  borderWidth,
  bgUrl,
  isImageFill,

  widthType,
  heightType,
  children,
  widthPercent,
  heightPercent,
  alignment,
  mainAlignment,
  crossAlignment,
  borderTLR,
  borderTRR,
  borderBLR,
  borderBRR,
  borderTW,
  borderTC,
  borderBW,
  borderBC,
  borderLW,
  borderLC,
  borderRW,
  borderRC,

  shadowSpreadRadius,
  shadowBlurRadius,
  shadowOffsetX,
  shadowOffsetY,
  shadowColor,
  isAbsoluteValue,

  onClick = "",
  action = "",
  navigation = "",

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType = "",
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  overflow,
  maxValue,
  minValue,
  midValue,
  zIndex
}) => {
  const tableWrapperRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [animationName, setAnimationName] = useState("");
  const animationNameRef = useRef("");
  const animationCountRef = useRef(0);

  const [hasAnimated, setHasAnimated] = useState(false);

  // Observer for when paragraph enters the viewport
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true); // Prevents the animation from running again
        }
      },
      { threshold: 0.2 }
    );

    if (tableWrapperRef.current) {
      observer.observe(tableWrapperRef.current);
    }

    return () => {
      if (tableWrapperRef.current) {
        observer.unobserve(tableWrapperRef.current);
      }
    };
  }, [hasAnimated, isVisible]);

    useEffect(() => {
      if (isAnimationP === "true") {
        runDynamicAnimations({
          ref: tableWrapperRef,
          isVisible,
          isAnimationP,
          animationType,
          animationDirection,
          animationEasing,
          animationIterations,
          animationDelay,
          isRevarsed,
          animationDuration,
          maxValue,
          minValue,
          midValue,
        });
      }
    }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes") {
      switch (action) {
        case "Navigate to":
          navigate(`/${navigation}`);
          break;
      }
    }
  };

  // Inline styles for the div container
  const containerStyle = {
     ...generateStyle({
            width,
            height,
            isAbsoluteValue,
            positionedLeft,
            positionedTop,
            positionedRight,
            positionedBottom,
            bgColor,
            bgUrl,
            isImageFill,
            color,
            borderRadius,
            borderTLR,
            borderTRR,
            borderBLR,
            borderBRR,
            borderWidth,
            borderColor,
            borderTW,
            borderBW,
            borderLW,
            borderRW,
            borderTC,
            borderBC,
            borderLC,
            borderRC,
            paddingLeft,
            paddingRight,
            paddingTop,
            paddingBottom,
            marginLeft,
            marginRight,
            marginTop,
            marginBottom,
            shadowOffsetX,
            shadowOffsetY,
            shadowBlurRadius,
            shadowSpreadRadius,
            shadowColor,
            overflow,
            mainAlignment,
            crossAlignment,
            onClick,
            zIndex,
          }),
    
    display: "flex",
    flexDirection: "column",
   
  
  };

  return (
    <div
      ref={tableWrapperRef}
      onClick={onClick === "Yes" ? handleClick : undefined}
      style={containerStyle}
    >
      {children}
    </div>
  );
};

// PropTypes for validation
QTableWrapper.propTypes = {
  width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  padding: PropTypes.string,
  paddingLeft: PropTypes.string,
  paddingTop: PropTypes.string,
  paddingRight: PropTypes.string,
  paddingBottom: PropTypes.string,
  margin: PropTypes.string,
  marginLeft: PropTypes.string,
  marginTop: PropTypes.string,
  marginRight: PropTypes.string,
  marginBottom: PropTypes.string,
  positionedLeft: PropTypes.string,
  positionedTop: PropTypes.string,
  positionedRight: PropTypes.string,
  positionedBottom: PropTypes.string,
  color: PropTypes.string,
  bgColor: PropTypes.string,
  borderRadius: PropTypes.string,
  borderColor: PropTypes.string,
  borderWidth: PropTypes.string,
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  shadowBlurRadius: PropTypes.string,
  shadowColor: PropTypes.string,
  shadowOffsetX: PropTypes.string,
  shadowOffsetY: PropTypes.string,
  shadowSpreadRadius: PropTypes.string,
  mainAlignment: PropTypes.string,
  crossAlignment: PropTypes.string,
  widthType: PropTypes.string,
  heightType: PropTypes.string,
  children: PropTypes.node,
};

export default QTableWrapper;
QTableWrapper.displayName = 'QTableWrapper';
