// created_files/React/react_export/src/qlib/qbutton/QButton.jsx
import React, { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { runDynamicAnimations } from "../../utils/animationUtils";
import { extractFontFamily } from "../../utils/helper";

const QButton = ({
  width,
  height,
  design,
  bgColor,
  headerText,
  style ,
  isLoading = false,
  iconLeft = null,
  iconRight = null,
  onPressed,
  onHover,
  onFocusChange,
  onLongPress,
  isAbsoluteValue,

  onClick = "",
  action = "",
  navigation = "",
  buttonType,

  // Animation Props
  maxValue,
  minValue,
  midValue,
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType,
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
    flexWrap,
  tailwaindClasses,
  boxShadow,
  foreground,
  textShadow,
  
}) => {
  const buttonRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [animationName, setAnimationName] = useState("");
  const animationNameRef = useRef("");
  const animationCountRef = useRef(0);

  const [hasAnimated, setHasAnimated] = useState(false);
  const font = extractFontFamily(tailwaindClasses);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true); // Prevents the animation from running again
        }
      },
      { threshold: 0.2 }
    );

    if (buttonRef.current) {
      observer.observe(buttonRef.current);
    }

    return () => {
      if (buttonRef.current) {
        observer.unobserve(buttonRef.current);
      }
    };
  }, [isVisible, hasAnimated]);

  useEffect(() => {
    if (isAnimationP === "true") {
      runDynamicAnimations({
        ref: buttonRef,
        isVisible,
        isAnimationP,
        animationType,
        animationDirection,
        animationEasing,
        animationIterations,
        animationDelay,
        isRevarsed,
        animationDuration,
        maxValue,
        minValue,
        midValue
      });
    }
  }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes") {
      switch (action) {
        case "Navigate to":
          navigate(`/${navigation}`);
          break;
      }
    }
  };

  const [isHovered, setIsHovered] = useState(false);
  const [isFocused, setIsFocused] = useState(false);

  // Handle bgColor as solid, linear, or radial gradient
  let effectiveBgColor = "transparent";
  let effectiveBgImage = "";

  if (bgColor) {
    if (bgColor.trim().startsWith("linear-gradient(") || bgColor.trim().startsWith("radial-gradient(")) {
      effectiveBgImage = bgColor;
    } else {
      effectiveBgColor = bgColor;
    }
  }
  
  const buttonStyles = {
    width: width,
    height: height,
    // backgroundColor: bgColor,
    backgroundColor: effectiveBgColor,
    backgroundImage: effectiveBgImage || undefined,
    cursor: "pointer",
    boxShadow: boxShadow,
    textShadow: textShadow,
    ...(font ? { fontFamily: font } : {}), // ✅ FIX
    ...(isAnimationP === "true" && animationType?.toLowerCase() !== "none" && !hasAnimated && { opacity: 0 }),

  };

  // Event handlers
  const handleMouseEnter = () => {
    if (onHover) onHover();
    setIsHovered(true);
  };

  const handleMouseLeave = () => setIsHovered(false);
  const handleFocus = () => {
    setIsFocused(true);
    if (onFocusChange) onFocusChange(true);
  };
  const handleBlur = () => {
    setIsFocused(false);
    if (onFocusChange) onFocusChange(false);
  };



  return (
    <>
        <button
          ref={buttonRef}
          style={{ ...buttonStyles, ...style }}
          onClick={onClick === "Yes" ? handleClick : undefined}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          onFocus={handleFocus}
          onBlur={handleBlur}
          disabled={isLoading}
          type={buttonType}
          className={`${tailwaindClasses}`}

        >
          {iconLeft && <span>{iconLeft}</span>}
          {headerText}
          {iconRight && <span>{iconRight}</span>}
        </button>
    </>
  );
};

export default QButton;
QButton.displayName = "QButton";

// created_files/Vue/vue_export/src/qlib/qbutton/QButton.vue
<script setup>
import { ref, onMounted, onUnmounted, watch, computed } from "vue";
import { useRouter } from "vue-router";
import { runDynamicAnimations } from "../../utils/animationUtils";
import { extractFontFamily } from "../../utils/helper";

const props = defineProps({
  width: String,
  height: String,
  design: String,
  bgColor: String,
  headerText: String,
  style: Object,
  isLoading: Boolean,
  iconLeft: Object,
  iconRight: Object,
  onPressed: Function,
  onHover: Function,
  onFocusChange: Function,
  onLongPress: Function,
  isAbsoluteValue: String,
  onClick: { type: String, default: "" },
  action: { type: String, default: "" },
  navigation: { type: String, default: "" },
  buttonType: String,

  // Animation Props
  maxValue: String,
  minValue: String,
  midValue: String,
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: String,
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  flexWrap: String,
  tailwaindClasses: { type: String, default: "" },
  boxShadow: String,
  foreground: String,
  textShadow: String,
});

const router = useRouter();
const buttonRef = ref(null);
const isVisible = ref(false);
const hasAnimated = ref(false);
const isHovered = ref(false);
const isFocused = ref(false);

const observer = ref(null);

const font = extractFontFamily(props.tailwaindClasses);

onMounted(() => {
  observer.value = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 },
  );

  if (buttonRef.value) {
    observer.value.observe(buttonRef.value);
  }
});

onUnmounted(() => {
  if (observer.value && buttonRef.value) {
    observer.value.unobserve(buttonRef.value);
  }
});

watch(isVisible, (val) => {
  if (props.isAnimationP === "true" && val) {
    runDynamicAnimations({
      ref: { current: buttonRef.value },
      isVisible: val,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      isRevarsed: props.isRevarsed,
      animationDuration: props.animationDuration,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });
  }
});

const handleClick = () => {
  if (props.onClick === "Yes") {
    switch (props.action) {
      case "Navigate to":
        router.push(`/${props.navigation}`);
        break;
    }
  }
  if (props.onPressed) props.onPressed();
};

const handleMouseEnter = () => {
  if (props.onHover) props.onHover();
  isHovered.value = true;
};
const handleMouseLeave = () => (isHovered.value = false);
const handleFocus = () => {
  isFocused.value = true;
  if (props.onFocusChange) props.onFocusChange(true);
};
const handleBlur = () => {
  isFocused.value = false;
  if (props.onFocusChange) props.onFocusChange(false);
};

const effectiveBg = computed(() => {
  let effectiveBgColor = "transparent";
  let effectiveBgImage = "";
  if (props.bgColor) {
    if (
      props.bgColor.trim().startsWith("linear-gradient(") ||
      props.bgColor.trim().startsWith("radial-gradient(")
    ) {
      effectiveBgImage = props.bgColor;
    } else {
      effectiveBgColor = props.bgColor;
    }
  }
  return { color: effectiveBgColor, image: effectiveBgImage };
});

const buttonStyles = computed(() => {
  return {
    width: props.width,
    height: props.height,
    backgroundColor: effectiveBg.value.color,
    backgroundImage: effectiveBg.value.image || undefined,
    cursor: "pointer",
    boxShadow: props.boxShadow,
    textShadow: props.textShadow,
    ...(font ? { fontFamily: font } : {}),
    ...(props.isAnimationP === "true" &&
      props.animationType?.toLowerCase() !== "none" &&
      !hasAnimated.value && { opacity: 0 }),
  };
});
</script>

<template>
  <button
    ref="buttonRef"
    :style="{ ...buttonStyles, ...style }"
    @click="handleClick"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
    @focus="handleFocus"
    @blur="handleBlur"
    :disabled="isLoading"
    :type="buttonType"
    :class="tailwaindClasses"
  >
    <span v-if="iconLeft"><component :is="iconLeft" /></span>
    {{ headerText }}
    <span v-if="iconRight"><component :is="iconRight" /></span>
  </button>
</template>
