// created_files/Vue/vue_export/src/qlib/qform/QForm.vue
<template>
  <form
    ref="formRef"
    :id="`form_${cms_form_Id}`"
    @submit.prevent="handleSubmit"
    :class="[classes, tailwaindClasses]"
    :style="formStyle"
  >
    <slot></slot>
  </form>
</template>

<script setup>
import { ref, onMounted, watch, computed, onUnmounted } from "vue";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  cms_form_Id: {
    type: String,
    required: true,
  },
  width: String,
  height: String,
  bgColor: String,
  bgUrl: String,
  isImageFill: [Boolean, String],
  isAbsoluteValue: [Boolean, String],
  tailwaindClasses: String,
  backgroundSize: String,
  boxShadow: String,
  textShadow: String,
  // Animation Props
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: String,
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  zIndex: [String, Number],
  // Events
  // onSubmit is emitted via plain 'submit' event on the form element?
  // But standard Vue form submit is @submit.
  // The react code takes an onSubmit prop.
  onSubmit: Function,
  maxValue: String,
  minValue: String,
  midValue: String,
});

const emit = defineEmits(["submit"]);

const formRef = ref(null);
const isVisible = ref(false);
const hasAnimated = ref(false);
const classes = ref("");

onMounted(() => {
  const observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 },
  );

  if (formRef.value) {
    observer.observe(formRef.value);
  }

  onUnmounted(() => {
    if (formRef.value) observer.unobserve(formRef.value);
  });
});

watch(isVisible, async (val) => {
  if (props.isAnimationP === "true" && val) {
    const reactRefMock = { current: formRef.value };
    await runDynamicAnimations({
      ref: reactRefMock,
      isVisible: val,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      animationDuration: props.animationDuration,
      isRevarsed: props.isRevarsed,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });

    classes.value = formRef.value.className;
  }
});

const handleSubmit = (e) => {
  // e.preventDefault() is handled by @submit.prevent in template
  emit("submit", e);
};

const formStyle = computed(() => {
  const styleProps = {
    width: props.width,
    height: props.height,
    bgColor: props.bgColor,
    bgUrl: props.bgUrl,
    isImageFill: props.isImageFill,
    isAbsoluteValue: props.isAbsoluteValue,
    zIndex: props.zIndex,
    backgroundSize: props.backgroundSize,
    boxShadow: props.boxShadow,
    textShadow: props.textShadow,
  };

  const filteredProps = Object.fromEntries(
    Object.entries(styleProps).filter(
      ([, v]) => v !== undefined && v !== null && v !== "",
    ),
  );

  return generateStyle(filteredProps);
});
</script>

// created_files/React/react_export/src/qlib/qform/QForm.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

/**
 * QForm — same structure as QDiv but acts as a form container
 * Supports animations, styles, and cms_form_Id for submission handling
 */
const QForm = ({
  cms_form_Id,
  width,
  height,
  bgColor,
  bgUrl,
  isImageFill,
  children,
  isAbsoluteValue,
  tailwaindClasses,
  backgroundSize,
  boxShadow,
  textShadow,

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType,
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  zIndex,
  maxValue,
  minValue,
  midValue,

  // Events
  onSubmit,
  onClick
}) => {
  const formRef = useRef(null);
  const [isVisible, setIsVisible] = useState(false);
  const [hasAnimated, setHasAnimated] = useState(false);
  const [classes, setClasses] = useState("");

  // ✅ Observe visibility for animation triggering
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true);
        }
      },
      { threshold: 0.2 }
    );

    if (formRef.current) observer.observe(formRef.current);
    return () => formRef.current && observer.unobserve(formRef.current);
  }, [hasAnimated]);

  // ✅ Handle dynamic animations when visible
  useEffect(() => {
    const applyAnimations = async () => {
      if (isAnimationP === "true" && isVisible) {
        await runDynamicAnimations({
          ref: formRef,
          isVisible,
          isAnimationP,
          animationType,
          animationDirection,
          animationEasing,
          animationIterations,
          animationDelay,
          animationDuration,
          isRevarsed,
          maxValue,
          minValue,
          midValue,
        });
        setClasses(formRef.current.className);
      }
    };
    applyAnimations();
  }, [isVisible]);

  // ✅ Handle submit (prevent default)
  const handleSubmit = (e) => {
    e.preventDefault();
    if (typeof onSubmit === "function") {
      onSubmit(e);
    }
  };

  // ✅ Style using helper
  const formStyle = {
    ...generateStyle(
      Object.fromEntries(
        Object.entries({
          width,
          height,
          bgColor,
          bgUrl,
          isImageFill,
          isAbsoluteValue,
          zIndex,
          backgroundSize,
          boxShadow,
          textShadow
        }).filter(([, v]) => v !== undefined && v !== null && v !== "")
      )
    ),
  };

  return (
    <form
      ref={formRef}
      id={`form_${cms_form_Id}`}
      onSubmit={handleSubmit}
     // onClick={onClick}
      style={formStyle}
      className={`${classes} ${tailwaindClasses || ""}`}
    >
      {children}
    </form>
  );
};

QForm.propTypes = {
  cms_form_Id: PropTypes.string.isRequired,
  width: PropTypes.string,
  height: PropTypes.string,
  bgColor: PropTypes.string,
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  children: PropTypes.node,
  isAbsoluteValue: PropTypes.bool,
  tailwaindClasses: PropTypes.string,
  backgroundSize: PropTypes.string,
  boxShadow: PropTypes.string,
  textShadow: PropTypes.string,
  isAnimationP: PropTypes.string,
  animationEasing: PropTypes.string,
  animationDirection: PropTypes.string,
  animationType: PropTypes.string,
  animationIterations: PropTypes.string,
  animationDelay: PropTypes.string,
  animationDuration: PropTypes.string,
  animationCurve: PropTypes.string,
  animationTargetPosition: PropTypes.string,
  isRevarsed: PropTypes.string,
  zIndex: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  onSubmit: PropTypes.func,
  onClick: PropTypes.func,
};

QForm.displayName = "QForm";
export default QForm;
