// created_files/Vue/vue_export/src/qlib/qdiv/QDiv.vue
<template>
  <div
    ref="divRef"
    @click="handleClick"
    :style="combinedStyle"
    :class="[classes, tailwaindClasses]"
  >
    <slot />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue';
import { useRouter } from 'vue-router';
// Adjust paths as necessary. In src/qlib/qdiv/QDiv.vue, utils are in ../../utils
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  width: String,
  height: String,
  bgColor: String,
  bgUrl: String,
  isImageFill: [Boolean, String],
  isAbsoluteValue: [Boolean, String],
  onClick: String,
  action: String,
  navigation: String,
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: String,
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  zIndex: [String, Number],
  tailwaindClasses: String,
  backgroundSize: String,
  boxShadow: String,
  textShadow: String,
  style: Object,
  maxValue: String,
  minValue: String
});

const divRef = ref(null);
const router = useRouter(); // Might be undefined if not set up, but okay.
const isVisible = ref(false);
const hasAnimated = ref(false);
const classes = ref("");

// Intersection Observer
onMounted(() => {
  const observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 }
  );

  if (divRef.value) observer.observe(divRef.value);
  // cleanup handle in onUnmounted if needed
});

// Animations
watch(isVisible, async (val) => {
    if (props.isAnimationP === "true" && val) {
       // Mocking React ref structure for the utility
       const reactRefMock = { current: divRef.value };

        await runDynamicAnimations({
          ref: reactRefMock,
          isVisible: val,
          isAnimationP: props.isAnimationP,
          animationType: props.animationType,
          animationDirection: props.animationDirection,
          animationEasing: props.animationEasing,
          animationIterations: props.animationIterations,
          animationDelay: props.animationDelay,
          animationDuration: props.animationDuration,
          isRevarsed: props.isRevarsed,
          maxValue: props.maxValue,
          minValue: props.minValue,
        });
        
        classes.value = divRef.value.className; // Update classes
    }
});

const handleClick = () => {
    if (props.onClick === "Yes" && props.action === "Navigate to" && props.navigation) {
      if (router) router.push(`/${props.navigation}`);
      else console.warn("Router not initialized");
    }
};

const combinedStyle = computed(() => {
    const generated = generateStyle({
        width: props.width,
        height: props.height,
        isAbsoluteValue: props.isAbsoluteValue,
        bgColor: props.bgColor,
        bgUrl: props.bgUrl,
        isImageFill: props.isImageFill,
        zIndex: props.zIndex,
        backgroundSize: props.backgroundSize,
        boxShadow: props.boxShadow,
        textShadow: props.textShadow
    });
    
    return { ...generated, ...props.style };
});

</script>

// created_files/React/react_export/src/qlib/qdiv/QDiv.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { useNavigate } from "react-router-dom";
import { generateStyle } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const QDiv = ({
  width,
  height,
  bgColor,
  bgUrl,
  isImageFill,
  children,
  isAbsoluteValue,
  onClick = "",
  action = "",
  navigation = "",

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType = "",
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  zIndex,
  tailwaindClasses,
  backgroundSize,
  boxShadow,
  textShadow,
  style
}) => {
  const divRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [hasAnimated, setHasAnimated] = useState(false);
  const [classes, setClasses] = useState("");

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true);
        }
      },
      { threshold: 0.2 }
    );

    if (divRef.current) observer.observe(divRef.current);
    return () => divRef.current && observer.unobserve(divRef.current);
  }, [hasAnimated]);

  useEffect(() => {
    const applyAnimations = async () => {
      if (isAnimationP === "true" && isVisible) {
        await runDynamicAnimations({
          ref: divRef,
          isVisible,
          isAnimationP,
          animationType,
          animationDirection,
          animationEasing,
          animationIterations,
          animationDelay,
          animationDuration,
          isRevarsed,
          maxValue,
          minValue,
        });

        setClasses(divRef.current.className);
      }
    };
    applyAnimations();
  }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes" && action === "Navigate to" && navigation) {
      navigate(`/${navigation}`);
    }
  };

  // Style only using allowed props
  const containerStyle = {
    ...generateStyle(
      Object.fromEntries(
        Object.entries({
          width,
          height,
          isAbsoluteValue,
          bgColor,
          bgUrl,
          isImageFill,
          zIndex,
          backgroundSize,
          boxShadow,
          textShadow
        }).filter(([, v]) => v !== undefined && v !== null && v !== "")
      )
    ),
    // display: "flex",
    // flexDirection: "column",
  };

  return (
    <div
      ref={divRef}
      onClick={onClick === "Yes" ? handleClick : undefined}
       style={{
          ...containerStyle,
          ...style
        }}
      className={`${classes} ${tailwaindClasses || ""}`}
    >
      {children}
    </div>
  );
};

QDiv.propTypes = {
  bgColor: PropTypes.string,
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  children: PropTypes.node,
  isAbsoluteValue: PropTypes.bool,
  onClick: PropTypes.string,
  action: PropTypes.string,
  navigation: PropTypes.string,
  isAnimationP: PropTypes.string,
  animationEasing: PropTypes.string,
  animationDirection: PropTypes.string,
  animationType: PropTypes.string,
  animationIterations: PropTypes.string,
  animationDelay: PropTypes.string,
  animationDuration: PropTypes.string,
  animationCurve: PropTypes.string,
  animationTargetPosition: PropTypes.string,
  isRevarsed: PropTypes.string,
  zIndex: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  tailwaindClasses: PropTypes.string,
  backgroundSize: PropTypes.string,
  boxShadow: PropTypes.string,
};

QDiv.displayName = "QDiv";
export default QDiv;
