// created_files/React/react_export/src/qlib/qimage/QImage.jsx
import React, { useEffect, useState, useRef } from "react";
import PropTypes from "prop-types";
import { defaultImageUrl } from "../../config";
import QImageAnimation from "../qimageanimation/QImageAnimation";
import { useNavigate } from "react-router-dom";
import { generateStyle, HexToFilter } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const QImage = ({
  width,
  height,
  bgUrl,
  bgColor,
  isAbsoluteValue,
  imageFit,
  color,
  onClick = "",
  action = "",
  navigation = "",

  // Animation Props
  isAnimationP,
  animationEasing,
  animationDirection,
  animationType,
  animationIterations,
  animationDelay,
  animationDuration,
  animationCurve,
  animationTargetPosition,
  isRevarsed,
  maxValue,
  minValue,
  midValue,
  overflow = "",
  zIndex,
  tailwaindClasses,
  seoAlt,
  seoTitle,
  boxShadow,
  foreground,
  backgroundSize,
  style,
}) => {
  const imgRef = useRef(null);
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [animationName, setAnimationName] = useState("");
  const animationNameRef = useRef("");
  const animationCountRef = useRef(0);

  const [hasAnimated, setHasAnimated] = useState(false);

  // Observer for when paragraph enters the viewport
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !hasAnimated) {
          setIsVisible(true);
          setHasAnimated(true); // Prevents the animation from running again
        }
      },
      { threshold: 0.2 }
    );

    if (imgRef.current) {
      observer.observe(imgRef.current);
    }

    return () => {
      if (imgRef.current) {
        observer.unobserve(imgRef.current);
      }
    };
  }, [isVisible, hasAnimated]);

  useEffect(() => {
    if (isAnimationP === "true") {
      runDynamicAnimations({
        ref: imgRef,
        isVisible,
        isAnimationP,
        animationType,
        animationDirection,
        animationEasing,
        animationIterations,
        animationDelay,
        isRevarsed,
        animationDuration,
        maxValue,
        minValue,
        midValue
      });
    }
  }, [isVisible]);

  const handleClick = () => {
    if (onClick === "Yes") {
      switch (action) {
        case "Navigate to":
          navigate(`/${navigation}`);
          break;
      }
    }
  };

    let objectFit;

    switch (backgroundSize) {
      case "cover":
        objectFit = "cover";
        break;
      case "contain":
        objectFit = "contain";
        break;
      case "fill":
        objectFit = "fill";
        break;
      case "fitHeight":
      case "fitWidth":
        objectFit = "contain";
        break;
      case "none":
        objectFit = "none";
        break;
      default:
        if (isAbsoluteValue !== "true") {
          objectFit = "scale-down";
        }
        break;
    }


  // Apply animation styles
  const imageStyle = {
    ...generateStyle({
         width,
         height,
         isAbsoluteValue,
         bgColor,
         color,
         overflow,
         onClick,
         zIndex,
         boxShadow,
       }),
       ...(foreground
         ? {
             background: foreground,
             WebkitBackgroundClip: "text",
             WebkitTextFillColor: "transparent",
           }
         : {}),
         objectFit: objectFit,
    // ...(isAnimationP === "true" && !hasAnimated && { opacity: 0 }),
    ...(isAnimationP === "true" && animationType?.toLowerCase() !== "none" && !hasAnimated && { opacity: 0 }),
  };

  const match = tailwaindClasses.match(/text-\[#([A-Fa-f0-9]{8})\]/);
    const textColorHex = match ? `#${match[1].toUpperCase()}` : null;

    const filterConverter = new HexToFilter();

    function hexToFilter(hex, useAdvanced = false) {
      return filterConverter.getFilter(hex, useAdvanced);
    }

  return (
    <>
    <img
        className={`${tailwaindClasses}`}
        ref={imgRef}
        onClick={onClick === "Yes" ? handleClick : undefined}
        src={bgUrl}
        alt={seoAlt}         // fallback to `alt` if `seoAlt` is not defined
        title={seoTitle}
       style={{
          ...imageStyle,
          ...style,
          filter: textColorHex? hexToFilter(textColorHex):""
        }}
      />

    </>
  );
};

// PropTypes for type-checking
QImage.propTypes = {
  bgUrl: PropTypes.string,
  height: PropTypes.string,
  width: PropTypes.string,

  animationDelay: PropTypes.string,
  animationDirection: PropTypes.string,
  animationDuration: PropTypes.string,
  animationEasing: PropTypes.string,
  animationIterations: PropTypes.string,
  animationTargetPosition: PropTypes.string,
  animationType: PropTypes.string,
  maxValue: PropTypes.string,
  minValue: PropTypes.string,
};

export default QImage;
QImage.displayName = "QImage";

// created_files/Vue/vue_export/src/qlib/qimage/QImage.vue
<script setup>
import { ref, watch, onMounted, onUnmounted, computed } from "vue";
import { useRouter } from "vue-router";
import { generateStyle, HexToFilter } from "../../utils/helper";
import { runDynamicAnimations } from "../../utils/animationUtils";

const props = defineProps({
  width: String,
  height: String,
  bgUrl: String,
  bgColor: String,
  isAbsoluteValue: String,
  imageFit: String,
  color: String,
  onClick: { type: String, default: "" },
  action: { type: String, default: "" },
  navigation: { type: String, default: "" },

  // Animation Props
  isAnimationP: String,
  animationEasing: String,
  animationDirection: String,
  animationType: String,
  animationIterations: String,
  animationDelay: String,
  animationDuration: String,
  animationCurve: String,
  animationTargetPosition: String,
  isRevarsed: String,
  maxValue: String,
  minValue: String,
  midValue: String,
  overflow: { type: String, default: "" },
  zIndex: String,
  tailwaindClasses: { type: String, default: "" },
  seoAlt: String,
  seoTitle: String,
  boxShadow: String,
  foreground: String,
  backgroundSize: String,
  style: Object,
});

const router = useRouter();
const imgRef = ref(null);
const isVisible = ref(false);
const hasAnimated = ref(false);

const observer = ref(null);

onMounted(() => {
  observer.value = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting && !hasAnimated.value) {
        isVisible.value = true;
        hasAnimated.value = true;
      }
    },
    { threshold: 0.2 },
  );

  if (imgRef.value) {
    observer.value.observe(imgRef.value);
  }
});

onUnmounted(() => {
  if (observer.value && imgRef.value) {
    observer.value.unobserve(imgRef.value);
  }
});

watch(isVisible, (val) => {
  if (props.isAnimationP === "true" && val) {
    runDynamicAnimations({
      ref: { current: imgRef.value }, // Adapt for util expecting React ref
      isVisible: val,
      isAnimationP: props.isAnimationP,
      animationType: props.animationType,
      animationDirection: props.animationDirection,
      animationEasing: props.animationEasing,
      animationIterations: props.animationIterations,
      animationDelay: props.animationDelay,
      isRevarsed: props.isRevarsed,
      animationDuration: props.animationDuration,
      maxValue: props.maxValue,
      minValue: props.minValue,
      midValue: props.midValue,
    });
  }
});

const handleClick = () => {
  if (props.onClick === "Yes") {
    switch (props.action) {
      case "Navigate to":
        router.push(`/${props.navigation}`);
        break;
    }
  }
};

const objectFitCtx = computed(() => {
  switch (props.backgroundSize) {
    case "cover":
      return "cover";
    case "contain":
      return "contain";
    case "fill":
      return "fill";
    case "fitHeight":
    case "fitWidth":
      return "contain";
    case "none":
      return "none";
    default:
      return props.isAbsoluteValue !== "true" ? "scale-down" : undefined;
  }
});

const imageStyle = computed(() => {
  return {
    ...generateStyle({
      width: props.width,
      height: props.height,
      isAbsoluteValue: props.isAbsoluteValue,
      bgColor: props.bgColor,
      color: props.color,
      overflow: props.overflow,
      onClick: props.onClick,
      zIndex: props.zIndex,
      boxShadow: props.boxShadow,
    }),
    ...(props.foreground
      ? {
          background: props.foreground,
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
        }
      : {}),
    objectFit: objectFitCtx.value,
    ...(props.isAnimationP === "true" &&
      props.animationType?.toLowerCase() !== "none" &&
      !hasAnimated.value && { opacity: 0 }),
  };
});

const filterStyle = computed(() => {
  const match = props.tailwaindClasses.match(/text-\[#([A-Fa-f0-9]{8})\]/);
  const textColorHex = match ? `#${match[1].toUpperCase()}` : null;

  if (textColorHex) {
    const filterConverter = new HexToFilter();
    return filterConverter.getFilter(textColorHex);
  }
  return "";
});
</script>

<template>
  <img
    :class="tailwaindClasses"
    ref="imgRef"
    @click="handleClick"
    :src="bgUrl"
    :alt="seoAlt"
    :title="seoTitle"
    :style="{
      ...imageStyle,
      ...style,
      filter: filterStyle,
    }"
  />
</template>
