// created_files/Vue/vue_export/src/qlib/qtab/QTabBar.vue
<script>
import { h, defineComponent, ref, mergeProps, Fragment } from 'vue'

export default defineComponent({
  name: 'QTabBar',
  props: {
    dividerColor: String,
    indicatorColor: String,
    tabHeaderSize: String,
    dividerSize: String,
    indicatorHeight: {
      type: String,
      default: "3px"
    },
    tailwaindClasses: {
      type: String,
      default: ""
    },
    tabDirection: {
      type: String,
      default: "Top" // Top, Bottom, Left, Right
    },
    bgColor: String
  },
  setup(props, { slots }) {
    const activeIndex = ref(0)

    const flattenChildren = (nodes) => {
      let flattened = []
      if (!nodes) return flattened
      
      nodes.forEach(node => {
        if (node.type === Fragment) {
          flattened.push(...flattenChildren(node.children))
        } else {
          flattened.push(node)
        }
      })
      return flattened
    }

    return () => {
      const headers = []
      const bodies = []
      
      const defaultSlot = slots.default ? slots.default() : []
      const children = flattenChildren(defaultSlot)

      children.forEach((child, index) => {
        // Check if child is QTab based on its name
        const childType = child.type
        const childName = childType?.name || childType?.__name || childType?.displayName

        if (childName === 'QTab') {
          // Access QTab's default slot content
          const tabContent = child.children && child.children.default ? child.children.default() : []
          const flatTabContent = flattenChildren(tabContent)
          
          const headerNode = flatTabContent.find(c => {
            const name = c.type?.name || c.type?.__name || c.type?.displayName
            return name === 'QTabHeader'
          })
          
          const bodyNode = flatTabContent.find(c => {
            const name = c.type?.name || c.type?.__name || c.type?.displayName
            return name === 'QTabBody'
          })

          if (headerNode) {
             const isVertical = props.tabDirection === "Left" || props.tabDirection === "Right"
             const headerTailClasses = `${headerNode.props?.tailwaindClasses || ""} ${
              isVertical ? "w-full" : "flex-1"
            }`.trim()
            
            headers.push(h(headerNode.type, mergeProps(headerNode.props || {}, {
              onClick: () => activeIndex.value = index,
              isActive: index === activeIndex.value,
              indicatorColor: props.indicatorColor,
              tabDirection: props.tabDirection,
              indicatorHeight: props.indicatorHeight,
              tailwaindClasses: headerTailClasses,
              key: `header-${index}`
            }), headerNode.children))
          }

          if (bodyNode) {
             const isVertical = props.tabDirection === "Left" || props.tabDirection === "Right"
             const bodyTailClasses = `${bodyNode.props?.tailwaindClasses || ""} flex-1 ${
              isVertical ? "h-full" : "w-full"
            }`.trim()

            // We only need to push/render if it matches the logic of "one body active"
            // But we push them all to the array to select later
            bodies.push(h(bodyNode.type, mergeProps(bodyNode.props || {}, {
              isVisible: index === activeIndex.value,
              tailwaindClasses: bodyTailClasses,
              key: `body-${index}`
            }), bodyNode.children))
          }
        }
      })

      const isVertical = props.tabDirection === "Left" || props.tabDirection === "Right"
      
      const directionMap = {
        Top: "flex-col",
        Bottom: "flex-col-reverse",
        Left: "flex-row",
        Right: "flex-row-reverse",
      }
      const flexion = directionMap[props.tabDirection] || "flex-col"

      // Header Container Style/Classes
      let headersClass = `${isVertical ? "flex-col border-r-[1px]" : "flex-row border-b-[1px]"} flex`
      let headersStyle = {}
      
      switch (props.tabDirection) {
        case "Top":
           headersStyle = { height: props.tabHeaderSize, borderBottomColor: props.dividerColor, borderBottomWidth: props.dividerSize }
           break
        case "Bottom":
           headersStyle = { height: props.tabHeaderSize, borderTopColor: props.dividerColor, borderTopWidth: props.dividerSize }
           break
        case "Left":
           headersStyle = { width: props.tabHeaderSize, borderRightColor: props.dividerColor, borderRightWidth: props.dividerSize }
           break
        case "Right":
           headersStyle = { width: props.tabHeaderSize, borderLeftColor: props.dividerColor, borderLeftWidth: props.dividerSize }
           break
      }

      return h('div', {
        class: `flex ${flexion} ${props.tailwaindClasses} QTabBar`,
        style: {
           background: props.bgColor,
           ...(isVertical ? { gap: props.dividerSize } : {})
        }
      }, [
        // Tab Headers
        h('div', {
          class: headersClass,
          style: headersStyle
        }, headers),
        
        // Active Tab Body
        bodies[activeIndex.value]
      ])
    }
  }
})
</script>

// created_files/React/react_export/src/qlib/qtab/QTabBar.jsx
import React, { useState, Children, cloneElement } from "react";

const QTabBar = ({
  dividerColor = "",
  indicatorColor = "",
  tabHeaderSize = "",
  dividerSize = "",
  indicatorHeight = "3px",
  children,
  tailwaindClasses = "",
  tabDirection = "Top", // Top | Bottom | Left | Right
  bgColor = "",
}) => {
  const [activeIndex, setActiveIndex] = useState(0);

  const headers = [];
  const bodies = [];

  Children.forEach(children, (child, index) => {
    if (child?.type?.displayName === "QTab") {
      const tabChildren = Children.toArray(child.props.children);

      const header = tabChildren.find(
        (c) =>
          c?.type?.displayName === "QTabHeader" ||
          c?.type?.name === "QTabHeader"
      );

      const body = tabChildren.find(
        (c) =>
          c?.type?.displayName === "QTabBody" ||
          c?.type?.name === "QTabBody"
      );

      if (header) {
        // Make headers fill space properly (equal width in horizontal, full width in vertical)
        const headerTailClasses = `${header.props.tailwaindClasses || ""} ${
          tabDirection === "Left" || tabDirection === "Right" ? "w-full" : "flex-1"
        }`.trim();

        headers.push(
          cloneElement(header, {
            onClick: () => setActiveIndex(index),
            isActive: index === activeIndex,
            indicatorColor,
            tabDirection,
            indicatorHeight,
            tailwaindClasses: headerTailClasses,
            key: `header-${index}`,
          })
        );
      }

      if (body) {
        // Body must take all remaining space → this is the main fix for distortion
        const bodyTailClasses = `${body.props.tailwaindClasses || ""} flex-1 ${
          tabDirection === "Left" || tabDirection === "Right" ? "h-full" : "w-full"
        }`.trim();

        bodies.push(
          cloneElement(body, {
            isVisible: index === activeIndex,
            tailwaindClasses: bodyTailClasses,
            key: `body-${index}`,
          })
        );
      }
    }
  });

  const isVertical = tabDirection === "Left" || tabDirection === "Right";

  // Main container direction
  const directionMap = {
    Top: "flex-col",
    Bottom: "flex-col-reverse",
    Left: "flex-row",
    Right: "flex-row-reverse",
  };

  // Headers container border + size (properly handles Bottom & Right)
  let headersClass = "flex ";
  let headersStyle = {};

  switch (tabDirection) {
    case "Top":
      headersClass += "flex-row border-b w-full";
      headersStyle = {
        height: tabHeaderSize,
        borderBottomColor: dividerColor,
        borderBottomWidth: dividerSize,
      };
      break;
    case "Bottom":
      headersClass += "flex-row border-t w-full";
      headersStyle = {
        height: tabHeaderSize,
        borderTopColor: dividerColor,
        borderTopWidth: dividerSize,
      };
      break;
    case "Left":
      headersClass += "flex-col border-r";
      headersStyle = {
        width: tabHeaderSize,
        borderRightColor: dividerColor,
        borderRightWidth: dividerSize,
      };
      break;
    case "Right":
      headersClass += "flex-col border-l";
      headersStyle = {
        width: tabHeaderSize,
        borderLeftColor: dividerColor,
        borderLeftWidth: dividerSize,
      };
      break;
  }

  return (
    <div
      className={`flex ${directionMap[tabDirection]} ${tailwaindClasses}`}
      style={{ background: bgColor }}
      // No extra gap — the border acts as the divider
    >
      {/* Tab headers */}
      <div className={headersClass} style={headersStyle}>
        {headers}
      </div>

      {/* Active tab body only */}
      {bodies[activeIndex]}
    </div>
  );
};

QTabBar.displayName = "QTabBar";
export default QTabBar;
