// created_files/Vue/vue_export/src/qlib/qtab/QTabBody.vue
<template>
  <div v-if="isVisible" :class="tailwaindClasses" :style="{ background: bgColor }">
    <slot></slot>
  </div>
</template>

<script setup>
defineOptions({
  name: 'QTabBody'
})

defineProps({
  isVisible: {
    type: Boolean,
    default: true
  },
  tailwaindClasses: {
    type: String,
    default: ""
  },
  bgColor: {
    type: String,
    default: ""
  }
})
</script>

// created_files/React/react_export/src/qlib/qtab/QTabBody.jsx
import React from "react";

const QTabBody = ({ children, isVisible, tailwaindClasses = "", bgColor = "" }) => {
  if (!isVisible) return null;
  return (
    <div className={tailwaindClasses} style={{ background: bgColor }}>
      {children}
    </div>
  );
};

QTabBody.displayName = "QTabBody";
export default QTabBody;
