// created_files/React/react_export/src/qlib/qtab/QTabHeader.jsx
const QTabHeader = ({
  onClick,
  isActive,
  indicatorColor,
  indicatorHeight,
  children,
  tailwaindClasses = "",
  tabDirection = "Top",
}) => {
  const getStyle = () => {
    if (!isActive) return {};

    switch (tabDirection) {
      case "Top":
        return { borderBottom: `${indicatorHeight} solid ${indicatorColor}` };
      case "Bottom":
        return { borderTop: `${indicatorHeight} solid ${indicatorColor}` };
      case "Left":
        return {
          backgroundColor: indicatorColor,
        //  paddingLeft: "8px",
        };
      case "Right":
        return {
          backgroundColor: indicatorColor,
        //  paddingRight: "8px",
        };
      default:
        return {};
    }
  };

  return (
    <div
      onClick={onClick}
      className={`cursor-pointer ${tailwaindClasses} ${isActive ? "font-bold" : ""}`}
      style={getStyle()}
    >
      {children}
    </div>
  );
};

QTabHeader.displayName = "QTabHeader";
export default QTabHeader;

// created_files/Vue/vue_export/src/qlib/qtab/QTabHeader.vue
<template>
  <div
    :class="[`cursor-pointer`, tailwaindClasses, isActive ? 'font-bold' : '']"
    :style="headerStyle"
  >
    <slot></slot>
  </div>
</template>

<script setup>
import { computed } from 'vue';

defineOptions({
  name: 'QTabHeader'
})

const props = defineProps({
  isActive: {
    type: Boolean,
    default: false
  },
  indicatorColor: {
    type: String,
    default: ""
  },
  indicatorHeight: {
    type: String,
    default: "3px" // defaulting to likely value if not passed, though QTabBar passes it
  },
  tailwaindClasses: {
    type: String,
    default: ""
  },
  tabDirection: {
    type: String,
    default: "Top"
  }
})

const headerStyle = computed(() => {
  if (!props.isActive) return {};

  switch (props.tabDirection) {
    case "Top":
      return { borderBottom: `${props.indicatorHeight} solid ${props.indicatorColor}` };
    case "Bottom":
      return { borderTop: `${props.indicatorHeight} solid ${props.indicatorColor}` };
    case "Left":
      return {
        backgroundColor: props.indicatorColor,
      };
    case "Right":
      return {
        backgroundColor: props.indicatorColor,
      };
    default:
      return {};
  }
})
</script>
